[package]
name = "aster-ip"
description = "IP link adapter for the Aster Mesh Protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aster-core = { version = "=0.1.0-alpha.1", path = "../aster-core", features = ["adapter-sdk"] }
getrandom.workspace = true
hkdf.workspace = true
sha2.workspace = true
socket2.workspace = true
subtle.workspace = true
tokio.workspace = true

[lints]
workspace = true
