//! Ubuntu systemd credential store provider for Aster provisioning.

#![forbid(unsafe_code)]

use aster_mesh::{
    MAX_UNPROTECTED_PROVISIONING_BYTES, ProfileProvisioningBundle, ProvisioningLoadId,
    ProvisioningLoadReceipt, ProvisioningSecretRef, ProvisioningSecretStoreError,
    UnprotectedProvisioning,
};
use zeroize::Zeroizing;

/// Stable identity of the selected D06 provider contract.
pub const PROVIDER_CONTRACT: &str = "aster-systemd-credential-store/v1";

/// Fixed systemd service credential consumed by the Aster agent.
pub const CREDENTIAL_NAME: &str = "aster-provisioning.bundle";

/// Exact size of the random identity in a v1 provider reference.
pub const PROVIDER_REFERENCE_ID_BYTES: usize = 32;

const PROVIDER_REFERENCE_MAGIC: &[u8; 8] = b"ASTRSDRF";
const PROVIDER_REFERENCE_VERSION: u16 = 1;
const PROVIDER_REFERENCE_HEADER_BYTES: usize = 8 + 2 + 2 + 8;
const PROVIDER_REFERENCE_OPAQUE_BYTES: usize =
    PROVIDER_REFERENCE_HEADER_BYTES + PROVIDER_REFERENCE_ID_BYTES;
const ASTER_REFERENCE_HEADER_BYTES: usize = 8 + 2 + 4;
const PROVIDER_SECRET_REF_BYTES: usize =
    ASTER_REFERENCE_HEADER_BYTES + PROVIDER_REFERENCE_OPAQUE_BYTES;

const CREDENTIAL_ENVELOPE_MAGIC: &[u8; 8] = b"ASTRSDCE";
const CREDENTIAL_ENVELOPE_VERSION: u16 = 1;
const CREDENTIAL_ENVELOPE_HEADER_BYTES: usize = 8 + 2 + 2 + 8 + 32 + 4 + 4;

/// Maximum exact v1 provider-envelope size accepted from systemd.
pub const MAX_CREDENTIAL_ENVELOPE_BYTES: usize = CREDENTIAL_ENVELOPE_HEADER_BYTES
    + PROVIDER_SECRET_REF_BYTES
    + MAX_UNPROTECTED_PROVISIONING_BYTES;

/// Constructs the canonical opaque reference for one provider generation.
///
/// The reference identity is caller-generated by the administration lane. A
/// zero generation is invalid and no random material is generated at runtime.
pub fn provisioning_secret_ref(
    generation: u64,
    reference_id: [u8; PROVIDER_REFERENCE_ID_BYTES],
) -> Result<ProvisioningSecretRef, ProvisioningSecretStoreError> {
    if generation == 0 {
        return Err(ProvisioningSecretStoreError::InvalidReference);
    }
    let mut opaque = Vec::with_capacity(PROVIDER_REFERENCE_OPAQUE_BYTES);
    opaque.extend_from_slice(PROVIDER_REFERENCE_MAGIC);
    opaque.extend_from_slice(&PROVIDER_REFERENCE_VERSION.to_be_bytes());
    opaque.extend_from_slice(&0_u16.to_be_bytes());
    opaque.extend_from_slice(&generation.to_be_bytes());
    opaque.extend_from_slice(&reference_id);
    ProvisioningSecretRef::from_opaque(opaque)
}

/// Encodes one canonical provider envelope for piping directly to
/// `systemd-creds encrypt` by the administration lane.
///
/// The returned buffer contains provisioning plaintext and zeroizes on drop.
pub fn encode_credential_envelope(
    secret_ref: &ProvisioningSecretRef,
    operation: ProvisioningLoadId,
    plaintext: &UnprotectedProvisioning,
) -> Result<Zeroizing<Vec<u8>>, ProvisioningSecretStoreError> {
    let generation = provider_generation(secret_ref)?;
    ProfileProvisioningBundle::from_bytes(plaintext.expose())
        .map_err(|_| ProvisioningSecretStoreError::Rejected)?;
    let encoded_ref = Zeroizing::new(secret_ref.to_bytes());
    let reference_len =
        u32::try_from(encoded_ref.len()).map_err(|_| ProvisioningSecretStoreError::TooLarge)?;
    let plaintext_len =
        u32::try_from(plaintext.len()).map_err(|_| ProvisioningSecretStoreError::TooLarge)?;
    let total_len = CREDENTIAL_ENVELOPE_HEADER_BYTES
        .checked_add(encoded_ref.len())
        .and_then(|length| length.checked_add(plaintext.len()))
        .ok_or(ProvisioningSecretStoreError::TooLarge)?;
    if total_len > MAX_CREDENTIAL_ENVELOPE_BYTES {
        return Err(ProvisioningSecretStoreError::TooLarge);
    }

    let mut encoded = Zeroizing::new(Vec::with_capacity(total_len));
    encoded.extend_from_slice(CREDENTIAL_ENVELOPE_MAGIC);
    encoded.extend_from_slice(&CREDENTIAL_ENVELOPE_VERSION.to_be_bytes());
    encoded.extend_from_slice(&0_u16.to_be_bytes());
    encoded.extend_from_slice(&generation.to_be_bytes());
    encoded.extend_from_slice(operation.as_bytes());
    encoded.extend_from_slice(&reference_len.to_be_bytes());
    encoded.extend_from_slice(&plaintext_len.to_be_bytes());
    encoded.extend_from_slice(&encoded_ref);
    encoded.extend_from_slice(plaintext.expose());
    Ok(encoded)
}

fn decode_credential_envelope(
    encoded: Zeroizing<Vec<u8>>,
    expected_operation: ProvisioningLoadId,
    expected_ref: &ProvisioningSecretRef,
) -> Result<ProvisioningLoadReceipt, ProvisioningSecretStoreError> {
    if encoded.len() > MAX_CREDENTIAL_ENVELOPE_BYTES {
        return Err(ProvisioningSecretStoreError::TooLarge);
    }
    if encoded.len() < CREDENTIAL_ENVELOPE_HEADER_BYTES
        || &encoded[..8] != CREDENTIAL_ENVELOPE_MAGIC
        || read_u16(&encoded[8..10])? != CREDENTIAL_ENVELOPE_VERSION
        || read_u16(&encoded[10..12])? != 0
    {
        return Err(ProvisioningSecretStoreError::Rejected);
    }

    let generation = read_u64(&encoded[12..20])?;
    if generation == 0 || &encoded[20..52] != expected_operation.as_bytes() {
        return Err(ProvisioningSecretStoreError::Rejected);
    }
    let reference_len = usize::try_from(read_u32(&encoded[52..56])?)
        .map_err(|_| ProvisioningSecretStoreError::Rejected)?;
    let plaintext_len = usize::try_from(read_u32(&encoded[56..60])?)
        .map_err(|_| ProvisioningSecretStoreError::Rejected)?;
    if reference_len != PROVIDER_SECRET_REF_BYTES {
        return Err(ProvisioningSecretStoreError::Rejected);
    }
    if plaintext_len > MAX_UNPROTECTED_PROVISIONING_BYTES {
        return Err(ProvisioningSecretStoreError::TooLarge);
    }
    if plaintext_len == 0 {
        return Err(ProvisioningSecretStoreError::Rejected);
    }
    let reference_end = CREDENTIAL_ENVELOPE_HEADER_BYTES
        .checked_add(reference_len)
        .ok_or(ProvisioningSecretStoreError::Rejected)?;
    let envelope_end = reference_end
        .checked_add(plaintext_len)
        .ok_or(ProvisioningSecretStoreError::Rejected)?;
    if envelope_end != encoded.len() {
        return Err(ProvisioningSecretStoreError::Rejected);
    }

    let envelope_ref = ProvisioningSecretRef::from_bytes(
        &encoded[CREDENTIAL_ENVELOPE_HEADER_BYTES..reference_end],
    )
    .map_err(|_| ProvisioningSecretStoreError::Rejected)?;
    if &envelope_ref != expected_ref
        || provider_generation(&envelope_ref)? != generation
        || provider_generation(expected_ref)? != generation
    {
        return Err(ProvisioningSecretStoreError::Rejected);
    }
    let plaintext_bytes = &encoded[reference_end..];
    ProfileProvisioningBundle::from_bytes(plaintext_bytes)
        .map_err(|_| ProvisioningSecretStoreError::Rejected)?;
    let plaintext = UnprotectedProvisioning::new(plaintext_bytes.to_vec())
        .map_err(|_| ProvisioningSecretStoreError::Rejected)?;
    Ok(ProvisioningLoadReceipt::new(
        expected_operation,
        expected_ref.clone(),
        plaintext,
    ))
}

fn provider_generation(
    secret_ref: &ProvisioningSecretRef,
) -> Result<u64, ProvisioningSecretStoreError> {
    let opaque = secret_ref.expose_opaque();
    if opaque.len() != PROVIDER_REFERENCE_OPAQUE_BYTES
        || &opaque[..8] != PROVIDER_REFERENCE_MAGIC
        || read_u16(&opaque[8..10])? != PROVIDER_REFERENCE_VERSION
        || read_u16(&opaque[10..12])? != 0
    {
        return Err(ProvisioningSecretStoreError::InvalidReference);
    }
    let generation = read_u64(&opaque[12..20])?;
    if generation == 0 {
        return Err(ProvisioningSecretStoreError::InvalidReference);
    }
    Ok(generation)
}

fn read_u16(bytes: &[u8]) -> Result<u16, ProvisioningSecretStoreError> {
    bytes
        .try_into()
        .map(u16::from_be_bytes)
        .map_err(|_| ProvisioningSecretStoreError::Rejected)
}

fn read_u32(bytes: &[u8]) -> Result<u32, ProvisioningSecretStoreError> {
    bytes
        .try_into()
        .map(u32::from_be_bytes)
        .map_err(|_| ProvisioningSecretStoreError::Rejected)
}

fn read_u64(bytes: &[u8]) -> Result<u64, ProvisioningSecretStoreError> {
    bytes
        .try_into()
        .map(u64::from_be_bytes)
        .map_err(|_| ProvisioningSecretStoreError::Rejected)
}

#[cfg(test)]
mod tests {
    use aster_mesh::{ProvisioningLoadId, ProvisioningSecretStoreError, UnprotectedProvisioning};
    use zeroize::Zeroizing;

    use super::{
        MAX_CREDENTIAL_ENVELOPE_BYTES, PROVIDER_REFERENCE_ID_BYTES, decode_credential_envelope,
        encode_credential_envelope, provisioning_secret_ref,
    };

    const GENERATION: u64 = 7;
    const OPERATION: ProvisioningLoadId = ProvisioningLoadId::new([0x2a; 32]);

    #[test]
    fn envelope_round_trip_is_canonical_and_exact() {
        // Break caught: changing the provider reference/envelope layout or
        // failing to echo the exact operation/reference would make installed
        // ciphertext incompatible with the selected v1 provider contract.
        let secret_ref = provisioning_secret_ref(GENERATION, [0x5a; PROVIDER_REFERENCE_ID_BYTES])
            .expect("valid provider reference");
        let mut expected_opaque = b"ASTRSDRF".to_vec();
        expected_opaque.extend_from_slice(&1_u16.to_be_bytes());
        expected_opaque.extend_from_slice(&0_u16.to_be_bytes());
        expected_opaque.extend_from_slice(&GENERATION.to_be_bytes());
        expected_opaque.extend_from_slice(&[0x5a; PROVIDER_REFERENCE_ID_BYTES]);
        assert_eq!(secret_ref.expose_opaque(), expected_opaque);

        let bundle =
            include_bytes!("../../../bindings/testdata/non-production-provisioning.bundle");
        let plaintext = UnprotectedProvisioning::new(bundle.to_vec()).expect("test bundle");
        let encoded = encode_credential_envelope(&secret_ref, OPERATION, &plaintext)
            .expect("encode provider envelope");

        assert_eq!(&encoded[..8], b"ASTRSDCE");
        assert_eq!(&encoded[8..10], &1_u16.to_be_bytes());
        assert_eq!(&encoded[10..12], &0_u16.to_be_bytes());
        assert_eq!(&encoded[12..20], &GENERATION.to_be_bytes());
        assert_eq!(&encoded[20..52], OPERATION.as_bytes());
        assert_eq!(
            u32::from_be_bytes(encoded[52..56].try_into().expect("reference length")),
            u32::try_from(secret_ref.encoded_len()).expect("bounded reference")
        );
        assert_eq!(
            u32::from_be_bytes(encoded[56..60].try_into().expect("inner length")),
            u32::try_from(bundle.len()).expect("bounded bundle")
        );

        let receipt = decode_credential_envelope(encoded, OPERATION, &secret_ref)
            .expect("decode provider envelope");
        assert_eq!(receipt.operation(), OPERATION);
        assert_eq!(receipt.secret_ref(), &secret_ref);
        assert_eq!(receipt.plaintext().expose(), bundle);
    }

    #[test]
    fn envelope_rejects_every_noncanonical_or_mismatched_boundary() {
        // Break caught: accepting one malformed header, length, reference,
        // generation, operation, or inner bundle would release unbound or
        // noncanonical provisioning plaintext to the node.
        let secret_ref = provisioning_secret_ref(GENERATION, [0x5a; PROVIDER_REFERENCE_ID_BYTES])
            .expect("valid provider reference");
        let other_ref =
            provisioning_secret_ref(GENERATION + 1, [0x6b; PROVIDER_REFERENCE_ID_BYTES])
                .expect("other provider reference");
        let bundle =
            include_bytes!("../../../bindings/testdata/non-production-provisioning.bundle");
        let plaintext = UnprotectedProvisioning::new(bundle.to_vec()).expect("test bundle");
        let canonical = encode_credential_envelope(&secret_ref, OPERATION, &plaintext)
            .expect("canonical envelope");

        let mut cases: Vec<(&str, Zeroizing<Vec<u8>>, ProvisioningLoadId, &_)> = Vec::new();

        let mut wrong_magic = canonical.clone();
        wrong_magic[0] ^= 1;
        cases.push(("wrong magic", wrong_magic, OPERATION, &secret_ref));

        let mut wrong_version = canonical.clone();
        wrong_version[9] = 2;
        cases.push(("wrong version", wrong_version, OPERATION, &secret_ref));

        let mut reserved = canonical.clone();
        reserved[11] = 1;
        cases.push(("reserved field", reserved, OPERATION, &secret_ref));

        let mut zero_generation = canonical.clone();
        zero_generation[12..20].fill(0);
        cases.push(("zero generation", zero_generation, OPERATION, &secret_ref));

        cases.push((
            "reference mismatch",
            canonical.clone(),
            OPERATION,
            &other_ref,
        ));
        cases.push((
            "operation mismatch",
            canonical.clone(),
            ProvisioningLoadId::new([0x33; 32]),
            &secret_ref,
        ));

        let mut malformed_reference = canonical.clone();
        malformed_reference[60] ^= 1;
        cases.push((
            "noncanonical reference",
            malformed_reference,
            OPERATION,
            &secret_ref,
        ));

        let mut wrong_reference_length = canonical.clone();
        wrong_reference_length[52..56].copy_from_slice(&1_u32.to_be_bytes());
        cases.push((
            "reference length",
            wrong_reference_length,
            OPERATION,
            &secret_ref,
        ));

        let mut wrong_inner_length = canonical.clone();
        wrong_inner_length[56..60].copy_from_slice(&1_u32.to_be_bytes());
        cases.push(("inner length", wrong_inner_length, OPERATION, &secret_ref));

        let mut corrupt_inner = canonical.clone();
        let last = corrupt_inner.len() - 1;
        corrupt_inner[last] ^= 1;
        cases.push((
            "invalid inner bundle",
            corrupt_inner,
            OPERATION,
            &secret_ref,
        ));

        let mut trailing = canonical.clone();
        trailing.push(0);
        cases.push(("trailing byte", trailing, OPERATION, &secret_ref));

        for (name, encoded, operation, expected_ref) in cases {
            assert_eq!(
                decode_credential_envelope(encoded, operation, expected_ref).expect_err(name),
                ProvisioningSecretStoreError::Rejected,
                "case {name}"
            );
        }

        let oversized = Zeroizing::new(vec![0; MAX_CREDENTIAL_ENVELOPE_BYTES + 1]);
        assert_eq!(
            decode_credential_envelope(oversized, OPERATION, &secret_ref)
                .expect_err("oversized envelope"),
            ProvisioningSecretStoreError::TooLarge
        );
        assert_eq!(
            provisioning_secret_ref(0, [0x5a; PROVIDER_REFERENCE_ID_BYTES])
                .expect_err("zero generation"),
            ProvisioningSecretStoreError::InvalidReference
        );
    }
}
